version: "3.8"

services:
  development:
    build: .
    stdin_open: true
    tty: true
    ports:
      - "9292:9292"
    volumes:
      - type: bind
        source: "."
        target: "/forknacular"
