services:
  development:
    build: .
    stdin_open: true
    tty: true
    develop:
      watch:
        - action: rebuild
          path: "./"
          target: "./forknacular"
    ports:
      - "9292:9292"
    volumes:
      - type: bind
        source: "."
        target: "/forknacular"
